#!/usr/bin/env python3
"""
Test the conjecture: j_min^spinorial = |[G,G]| / 2 for non-obstructed groups.

For each non-obstructed finite subgroup G ⊂ SU(2), find the smallest j
such that a scalar spinorial sector has nonzero multiplicity.

Groups tested:
  - Cyclic Z_{2n} (n = 1,2,3,5,7): [G,G] = {1}, predict j_min = 1/2
  - Dicyclic Dic_N (N = 3,5,7,11): [G,G] = Z_N, predict j_min = N/2

If j_min = |[G,G]|/2 holds universally, this is a new structural result.

NOTE: This is actually a CONSEQUENCE of the Restoration Threshold Theorem
(tests/6_restoration_threshold.py): dim_min = |[G,G]| + 1, so
j_min = (dim_min - 1)/2 = |[G,G]|/2. The spectral formulation is new.

RAW OUTPUT:
===========
======================================================================
TEST: j_min^spinorial = |[G,G]| / 2 ?
======================================================================

--- Cyclic groups Z_{2n} ---
       Group    |G|  |[G,G]|   predict    actual  match
-------------------------------------------------------
       Z_{2}      2        1       0.5       0.5      ✓
       Z_{4}      4        1       0.5       0.5      ✓
       Z_{6}      6        1       0.5       0.5      ✓
      Z_{10}     10        1       0.5       0.5      ✓
      Z_{14}     14        1       0.5       0.5      ✓
      Z_{20}     20        1       0.5       0.5      ✓

--- Dicyclic groups Dic_N (N odd) ---
       Group    |G|  |[G,G]|   predict    actual  match
-------------------------------------------------------
     Dic_{1}      4        1       0.5       0.5      ✓
     Dic_{3}     12        3       1.5       1.5      ✓
     Dic_{5}     20        5       2.5       2.5      ✓
     Dic_{7}     28        7       3.5       3.5      ✓
     Dic_{9}     36        9       4.5       4.5      ✓
    Dic_{11}     44       11       5.5       5.5      ✓

--- Dicyclic groups Dic_N (N even, should be obstructed) ---
       Group    |G|  |[G,G]|    obstr?
----------------------------------------
     Dic_{2}      8        2       YES
     Dic_{4}     16        4       YES
     Dic_{6}     24        6       YES

======================================================================
SUMMARY
======================================================================

Conjecture j_min = |[G,G]|/2: CONFIRMED ✓

Groups tested: 12
  Matches: 12
  Failures: 0

INTERPRETATION:
  The minimal spinorial angular momentum is determined by the
  commutator subgroup size:

    j_min^spinorial = |[G,G]| / 2

  For cyclic groups: |[G,G]| = 1 → j_min = 1/2 (standard SO(3) value)
  For Dic_N (N odd): |[G,G]| = N → j_min = N/2 (shifted by quotient)

  Physical meaning: the commutator subgroup "delays" the onset of
  spinorial states. Larger [G,G] → higher minimum spinorial energy:

    E_min^spinorial = j_min(j_min + 1) = (N/2)(N/2 + 1)

  This is a spectral signature of the group structure, not just
  of the obstruction/non-obstruction dichotomy.
"""
import sys
sys.path.insert(0, '/Users/alextoader/Sites/st_spinorial_obstruction')

import numpy as np
from src.quaternion import qkey, qmul
from src.group import compute_conjugacy_classes, compute_commutator_subgroup


def chi_su2(j, trace):
    """SU(2) spin-j character at given trace."""
    d = int(2 * j + 1)
    if abs(trace - 2) < 1e-10:
        return float(d)
    if abs(trace + 2) < 1e-10:
        return float(d * ((-1) ** int(round(2 * j))))
    ha = np.arccos(np.clip(trace / 2, -1, 1))
    if abs(np.sin(ha)) < 1e-14:
        return float(d)
    return np.sin(d * ha) / np.sin(ha)


def build_cyclic(n):
    """Build Z_{2n} ⊂ SU(2) as unit quaternions.
    Elements: e^{iπk/n} = (cos(πk/n), 0, 0, sin(πk/n)) for k = 0,...,2n-1.
    """
    elements = []
    for k in range(2 * n):
        angle = k * np.pi / n
        q = np.array([np.cos(angle), 0, 0, np.sin(angle)])
        elements.append(q)
    return np.array(elements)


def build_dicyclic(N):
    """Build Dic_N ⊂ SU(2) (order 4N) as unit quaternions.
    Generated by a = e^{iπ/N} (order 2N) and x = j (with x² = a^N = -1).
    Elements: {a^k, x·a^k} for k = 0,...,2N-1.
    """
    elements = []
    for k in range(2 * N):
        angle = k * np.pi / N
        q = np.array([np.cos(angle), 0, 0, np.sin(angle)])
        elements.append(q)
    x = np.array([0, 0, 1, 0], dtype=float)
    for k in range(2 * N):
        angle = k * np.pi / N
        ak = np.array([np.cos(angle), 0, 0, np.sin(angle)])
        elements.append(qmul(x, ak))
    return np.array(elements)


def find_jmin_spinorial(elements, max_j=20):
    """Find the smallest half-integer j with a scalar spinorial sector.

    Returns (j_min, details) or (None, details) if not found up to max_j.
    """
    # Conjugacy classes
    classes = compute_conjugacy_classes(elements)
    classes.sort(key=lambda c: -c['trace'])
    sizes = [c['size'] for c in classes]
    G = sum(sizes)
    sizes_arr = np.array(sizes, dtype=float)

    # Commutator subgroup
    comm = compute_commutator_subgroup(elements)
    comm_keys = set(comm.keys())
    comm_size = len(comm)

    # Check if obstructed
    mk = qkey(np.array([-1, 0, 0, 0], dtype=float))
    obstructed = mk in comm_keys

    if obstructed:
        return None, {'obstructed': True, 'G': G, 'comm_size': comm_size}

    # Build ALL 1D characters via quotient map G → G/[G,G]
    # For cyclic groups: abelian, [G,G] = {1}, all elements are their own coset
    # For dicyclic Dic_N: [G,G] = Z_N, quotient = Z_{4N}/Z_N = Z_4
    # General approach: assign character values per element

    abel_size = G // comm_size

    # For each class, find a representative element
    # Build character table of abelianization
    # Simple approach: use inner product formula directly

    # For each potential 1D character, it must factor through G/[G,G]
    # The abelianization is cyclic (for SU(2) subgroups), so characters are
    # χ_k(g) = ω^k where ω = e^{2πi/|Abel|} and the map is G → Z_|Abel|

    # We need to identify the quotient map g ↦ coset of g in G/[G,G]
    # Approach: for cyclic Z_{2n}, all chars are known analytically
    # For dicyclic Dic_N (N odd), we computed chars in script 15

    # General numeric approach: construct all 1D characters by trial
    # A 1D char χ: G → C* satisfies χ(gh) = χ(g)χ(h) and |χ(g)| = 1
    # On a conjugacy class, χ is constant. So χ is determined by its values
    # on class representatives.

    # Actually, simplest: use the multiplicity formula directly.
    # For EVERY possible 1D char, the multiplicity of χ in V_j is:
    #   m(χ, j) = (1/|G|) Σ_g χ(g)* · χ_j(g)
    # We need to iterate over 1D characters.

    # For cyclic Z_{2n}: chars are χ_k(a^m) = e^{2πikm/(2n)} for k=0,...,2n-1
    # Spinorial: χ_k(-1) = χ_k(a^n) = e^{πik} = (-1)^k → spinorial iff k odd.

    # For Dic_N: chars are as computed in script 15.

    # Generic approach: construct characters from group structure
    # Since all our groups have abelianization that is cyclic (Z_m),
    # we can find a generator of G/[G,G] and build from there.

    # SIMPLEST: iterate over all elements, find one that generates G/[G,G]
    # by checking that its image in Abel has maximal order.

    # Find quotient map: for each element, determine its coset in G/[G,G]
    # Coset of g = {g·c : c ∈ [G,G]}
    elem_to_coset = {}
    cosets = []
    for e in elements:
        k = qkey(e)
        if k in elem_to_coset:
            continue
        # Compute coset g·[G,G]
        coset = set()
        for ck, cv in comm.items():
            prod = qmul(e, cv)
            coset.add(qkey(prod))
        # Check if this coset already exists
        found = False
        for ci, existing in enumerate(cosets):
            if existing & coset:
                for kk in coset:
                    elem_to_coset[kk] = ci
                found = True
                break
        if not found:
            ci = len(cosets)
            cosets.append(coset)
            for kk in coset:
                elem_to_coset[kk] = ci

    # Now coset index for each element
    # Build character values: abelianization is Z_{abel_size}
    # Need to find which coset maps to which element of Z_{abel_size}

    # Find a generator: element whose coset has maximal order in quotient
    # Try each coset, find order in quotient group
    # Quotient multiplication: coset(g) * coset(h) = coset(gh)
    # Element g has order d in quotient if g^d ∈ [G,G] and d minimal

    gen_coset = None
    for e in elements:
        k = qkey(e)
        ci = elem_to_coset[k]
        # Compute order of ci in quotient
        power = e.copy()
        for d in range(1, abel_size + 1):
            pk = qkey(power)
            if pk in comm_keys:
                if d == abel_size:
                    gen_coset = ci
                    gen_elem = e.copy()
                break
            power = qmul(power, e)
        if gen_coset is not None:
            break

    if gen_coset is None:
        # Fallback: try all elements
        for e in elements:
            k = qkey(e)
            power = e.copy()
            for d in range(1, abel_size + 1):
                pk = qkey(power)
                if pk in comm_keys:
                    if d == abel_size:
                        gen_coset = elem_to_coset[k]
                        gen_elem = e.copy()
                    break
                power = qmul(power, e)
            if gen_coset is not None:
                break

    # Assign Z_{abel_size} labels to cosets
    # gen_coset → 1, gen^2 → 2, etc.
    coset_label = {}
    power = np.array([1, 0, 0, 0], dtype=float)
    for d in range(abel_size):
        ci = elem_to_coset[qkey(power)]
        coset_label[ci] = d
        power = qmul(power, gen_elem)

    # Now build all 1D characters
    # χ_k(g) = ω^{k·label(g)} where ω = e^{2πi/abel_size}
    omega = np.exp(2j * np.pi / abel_size)

    # Assign class-level character values
    class_labels = []
    for c in classes:
        rep_key = list(c['keys'])[0]
        ci = elem_to_coset[rep_key]
        class_labels.append(coset_label[ci])
    class_labels = np.array(class_labels)

    # Find spinorial characters (χ(-1) = -1)
    # -1 is in some class; find its label
    for i, c in enumerate(classes):
        if abs(c['trace'] + 2) < 1e-10:
            minus_one_label = class_labels[i]
            break

    spinorial_chars = []
    for k in range(abel_size):
        chi_minus_one = omega ** (k * minus_one_label)
        if chi_minus_one.real < -0.5:  # = -1
            spinorial_chars.append(k)

    if not spinorial_chars:
        return None, {'obstructed': True, 'G': G, 'comm_size': comm_size,
                      'note': 'no spinorial 1D chars found'}

    # Now find j_min
    for two_j in range(1, 2 * max_j + 1, 2):  # half-integer j only
        j = two_j / 2.0
        chi_Vj = np.array([chi_su2(j, c['trace']) for c in classes])

        for k in spinorial_chars:
            chi_k = omega ** (k * class_labels)
            m = np.sum(chi_k.conj() * chi_Vj * sizes_arr) / G
            m_r = round(m.real)
            if m_r > 0:
                return j, {'G': G, 'comm_size': comm_size,
                           'abel_size': abel_size,
                           'n_spinorial_chars': len(spinorial_chars),
                           'char_index': k, 'mult': m_r}

    return None, {'G': G, 'comm_size': comm_size, 'not_found_up_to': max_j}


def main():
    print("=" * 70)
    print("TEST: j_min^spinorial = |[G,G]| / 2 ?")
    print("=" * 70)

    results = []

    # Cyclic groups Z_{2n}
    print("\n--- Cyclic groups Z_{2n} ---")
    print(f"{'Group':>12}  {'|G|':>5}  {'|[G,G]|':>7}  {'predict':>8}  {'actual':>8}  {'match':>5}")
    print("-" * 55)

    for n in [1, 2, 3, 5, 7, 10]:
        elements = build_cyclic(n)
        j_min, info = find_jmin_spinorial(elements)
        comm_size = info.get('comm_size', '?')
        predict = comm_size / 2.0 if isinstance(comm_size, (int, float)) and comm_size > 0 else '?'

        if info.get('obstructed'):
            actual = 'OBSTR'
            match = '-'
        elif j_min is not None:
            actual = f'{j_min:.1f}'
            match = '✓' if abs(j_min - predict) < 1e-10 else '✗'
        else:
            actual = f'>20'
            match = '?'

        name = f'Z_{{{2*n}}}'
        print(f'{name:>12}  {len(elements):5d}  {comm_size:>7}  {predict:>8}  {actual:>8}  {match:>5}')
        results.append((name, len(elements), comm_size, predict, j_min, match))

    # Dicyclic groups Dic_N (N odd = non-obstructed)
    print("\n--- Dicyclic groups Dic_N (N odd) ---")
    print(f"{'Group':>12}  {'|G|':>5}  {'|[G,G]|':>7}  {'predict':>8}  {'actual':>8}  {'match':>5}")
    print("-" * 55)

    for N in [1, 3, 5, 7, 9, 11]:
        elements = build_dicyclic(N)
        j_min, info = find_jmin_spinorial(elements)
        comm_size = info.get('comm_size', '?')
        predict = comm_size / 2.0 if isinstance(comm_size, (int, float)) and comm_size > 0 else '?'

        if info.get('obstructed'):
            actual = 'OBSTR'
            match = '-'
        elif j_min is not None:
            actual = f'{j_min:.1f}'
            match = '✓' if abs(j_min - predict) < 1e-10 else '✗'
        else:
            actual = f'>20'
            match = '?'

        name = f'Dic_{{{N}}}'
        print(f'{name:>12}  {len(elements):5d}  {comm_size:>7}  {predict:>8}  {actual:>8}  {match:>5}')
        results.append((name, len(elements), comm_size, predict, j_min, match))

    # Dicyclic groups Dic_N (N even = obstructed) — verify
    print("\n--- Dicyclic groups Dic_N (N even, should be obstructed) ---")
    print(f"{'Group':>12}  {'|G|':>5}  {'|[G,G]|':>7}  {'obstr?':>8}")
    print("-" * 40)

    for N in [2, 4, 6]:
        elements = build_dicyclic(N)
        j_min, info = find_jmin_spinorial(elements)
        comm_size = info.get('comm_size', '?')
        obstr = 'YES' if info.get('obstructed') else 'NO'
        name = f'Dic_{{{N}}}'
        print(f'{name:>12}  {len(elements):5d}  {comm_size:>7}  {obstr:>8}')

    # Summary
    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)

    all_match = all(r[5] == '✓' for r in results if r[5] in ('✓', '✗'))
    print(f"\nConjecture j_min = |[G,G]|/2: {'CONFIRMED ✓' if all_match else 'FAILED ✗'}")
    print(f"\nGroups tested: {len(results)}")
    print(f"  Matches: {sum(1 for r in results if r[5] == '✓')}")
    print(f"  Failures: {sum(1 for r in results if r[5] == '✗')}")

    if all_match:
        print("""
INTERPRETATION:
  The minimal spinorial angular momentum is determined by the
  commutator subgroup size:

    j_min^spinorial = |[G,G]| / 2

  For cyclic groups: |[G,G]| = 1 → j_min = 1/2 (standard SO(3) value)
  For Dic_N (N odd): |[G,G]| = N → j_min = N/2 (shifted by quotient)

  Physical meaning: the commutator subgroup "delays" the onset of
  spinorial states. Larger [G,G] → higher minimum spinorial energy:

    E_min^spinorial = j_min(j_min + 1) = (N/2)(N/2 + 1)

  This is a spectral signature of the group structure, not just
  of the obstruction/non-obstruction dichotomy.
""")


if __name__ == '__main__':
    main()
