#!/usr/bin/env python3
"""
Part A: Analytic proof that -1 ∈ [G,G] ⟹ no spinorial 1D character.
Part B: H²(π₁, U(1)) — cohomological classification of phases.

PART A: THE THREE-LINE PROOF
=============================

LEMMA: For any finite group G and any 1D character χ: G → U(1),
  χ(g) = 1 for all g ∈ [G,G].

PROOF:
  For any commutator [a,b] = aba⁻¹b⁻¹:
    χ([a,b]) = χ(a)χ(b)χ(a)⁻¹χ(b)⁻¹ = 1
  since U(1) is abelian (all factors cancel).
  [G,G] is generated by commutators, and χ is a homomorphism,
  so χ|_{[G,G]} ≡ 1.  □

COROLLARY: If -1 ∈ [G,G], then χ(-1) = 1 for every 1D character χ.
  No 1D character can be spinorial (χ(-1) = -1).

This is the COMPLETE analytic proof of the obstruction theorem.
No classification of finite groups is needed. No case analysis.
The result holds for ANY finite group, not just subgroups of SU(2).

PART B: COHOMOLOGICAL PERSPECTIVE
==================================

The quantization sectors on M with π₁ = G are classified by:
  Hom(G, U(1)) = Hom(G/[G,G], U(1)) = Ĝ_ab

This is H¹(G, U(1)) — the first cohomology with U(1) coefficients.
(Not H², which classifies projective representations / central extensions.)

The obstruction says: if -1 ∈ [G,G], the image of -1 in G_ab is trivial,
so no homomorphism can send -1 to -1 ∈ U(1).

H² perspective: H²(G, U(1)) classifies projective representations
(central extensions of G by U(1)). Not all vector bundle sectors come
from H²: linear higher-rank reps are classified by Rep(G).
Spinorial content of V_j|_{2H} is carried by higher-dimensional irreps
of 2H, which are intrinsically rank > 1 and cannot be reduced to 1D.

RAW OUTPUT:
===========

PART A: ANALYTIC PROOF
  LEMMA: χ([a,b]) = 1 (U(1) abelian). So χ|_{[G,G]} ≡ 1.
  COROLLARY: -1 ∈ [G,G] ⟹ χ(-1) = 1. No spinorial 1D char.
  CONVERSE: -1 ∉ [G,G] ⟹ ∃ χ with χ(-1) = -1.
  COMBINED: -1 ∈ [G,G] ⟺ no scalar spinorial sector. IFF proved.
  VERIFIED: 5 groups, all [a,b] ∈ [G,G] ✓

PART B: H¹(G, U(1)) = Ĝ_ab = scalar sectors
  2T: 3, 2O: 2, 2I: 1, Dic₃: 4, Dic₅: 4

PART C: H²(G, U(1)) = Schur multiplier = projective classes
  2T: 0, 2O: Z₂, 2I: Z₂, Dic₃: Z₂, Dic₅: Z₂, Q₈: 0

PART D: Fate of spinorial states on SO(3)/O
  105 total states (j≤6.5): 5 scalar (4.8%), 100 in vector bundles (95.2%)
  Spinorial content survives in higher-rank irreps, not accessible to scalar quantization.

"""
import sys
sys.path.insert(0, '/Users/alextoader/Sites/st_spinorial_obstruction')

import numpy as np
from src.quaternion import qkey, qmul, qinv
from src.group import (build_binary_tetrahedral, build_binary_octahedral,
                       build_binary_icosahedral,
                       compute_conjugacy_classes, compute_commutator_subgroup)


def build_dicyclic(N):
    """Build Dic_N ⊂ SU(2) (order 4N)."""
    elements = []
    for k in range(2 * N):
        angle = k * np.pi / N
        elements.append(np.array([np.cos(angle), 0, 0, np.sin(angle)]))
    x = np.array([0, 0, 1, 0], dtype=float)
    for k in range(2 * N):
        angle = k * np.pi / N
        ak = np.array([np.cos(angle), 0, 0, np.sin(angle)])
        elements.append(qmul(x, ak))
    return np.array(elements)


def main():
    print("=" * 70)
    print("ANALYTIC PROOF AND COHOMOLOGICAL PERSPECTIVE")
    print("=" * 70)

    # ============================================================
    # PART A: THE THREE-LINE PROOF
    # ============================================================
    print("\n" + "=" * 70)
    print("PART A: ANALYTIC PROOF (NO CLASSIFICATION NEEDED)")
    print("=" * 70)

    print("""
  LEMMA: For any finite group G and 1D character χ: G → U(1):
    χ(g) = 1  for all g ∈ [G,G].

  PROOF:
    χ([a,b]) = χ(a)χ(b)χ(a⁻¹)χ(b⁻¹)
             = χ(a)χ(b)χ(a)⁻¹χ(b)⁻¹
             = 1                          (U(1) is abelian)

    [G,G] = ⟨{[a,b] : a,b ∈ G}⟩, and χ is a homomorphism,
    so χ|_{[G,G]} ≡ 1.  □

  COROLLARY: -1 ∈ [G,G]  ⟹  χ(-1) = 1  for all 1D chars χ.
    No scalar spinorial sector exists.

  CONVERSE: -1 ∉ [G,G]  ⟹  -1 has nontrivial image in G_ab = G/[G,G].
    Since G_ab is abelian and -1 has order 2 in G, its image has
    order 1 or 2 in G_ab. If order 2: ∃ χ with χ(-1) = -1.
    Order 1 means -1 ∈ [G,G], contradicting assumption.
    So: ∃ spinorial 1D character.  □

  COMBINED: -1 ∈ [G,G]  ⟺  no scalar spinorial sector.
  This is an IFF, proved without any classification.
""")

    # Verification
    print("  VERIFICATION: χ([a,b]) = 1 for explicit commutators")
    print("  ─" * 30)

    groups = [
        ("2T", build_binary_tetrahedral()),
        ("2O", build_binary_octahedral()),
        ("2I", build_binary_icosahedral()),
        ("Dic₃", build_dicyclic(3)),
        ("Dic₅", build_dicyclic(5)),
    ]

    for name, elements in groups:
        # Compute a few commutators and verify they map to 1
        # under the quotient map G → G_ab
        comm = compute_commutator_subgroup(elements)
        comm_keys = set(comm.keys())
        G = len(elements)
        abel_size = G // len(comm)

        # Take 50 random pairs, compute [a,b], verify it's in [G,G]
        np.random.seed(42)
        n_test = 50
        all_in_comm = True
        for _ in range(n_test):
            i, j = np.random.randint(0, G, 2)
            a, b = elements[i], elements[j]
            ab = qmul(qmul(a, b), qmul(qinv(a), qinv(b)))
            if qkey(ab) not in comm_keys:
                all_in_comm = False
                break

        print(f"    {name:>5}: |G|={G:3d}, |[G,G]|={len(comm):3d}, "
              f"|Abel|={abel_size:2d}, "
              f"all [a,b] ∈ [G,G]: {'✓' if all_in_comm else '✗'}")

    # ============================================================
    # PART B: H¹ vs H² — WHAT CLASSIFIES WHAT
    # ============================================================
    print("\n" + "=" * 70)
    print("PART B: COHOMOLOGICAL CLASSIFICATION")
    print("=" * 70)

    print("""
  For a space M with π₁(M) = G:

  H¹(G, U(1)) = Hom(G, U(1))    — classifies SCALAR quantization sectors
                                    (line bundles / 1D representations)

  H²(G, U(1))                    — classifies PROJECTIVE representations
                                    (central extensions of G by U(1))
                                    Not all vector bundles come from H².

  SCALAR SECTORS:
    H¹(G, U(1)) = Hom(G/[G,G], U(1)) = Ĝ_ab  (Pontryagin dual)
    |H¹| = |G_ab| = |G/[G,G]| = κ
""")

    print("  Explicit computation:")
    print(f"  {'Group':>8}  {'|G|':>4}  {'|[G,G]|':>7}  {'|Abel|':>5}  "
          f"{'H¹':>4}  {'scalar sectors':>15}")
    print(f"  {'─'*55}")

    for name, elements in groups:
        comm = compute_commutator_subgroup(elements)
        G = len(elements)
        abel = G // len(comm)

        # H¹ = Ĝ_ab, which has same order as G_ab
        # For cyclic G_ab: Ẑ_n ≅ Z_n
        print(f"  {name:>8}  {G:4d}  {len(comm):7d}  {abel:5d}  "
              f"{abel:4d}  {abel} sector(s)")

    # ============================================================
    # PART C: H² — PROJECTIVE REPRESENTATIONS
    # ============================================================
    print("\n" + "=" * 70)
    print("PART C: H²(G, U(1)) AND VECTOR BUNDLE SECTORS")
    print("=" * 70)

    print("""
  H²(G, U(1)) for finite G classifies:
    - Central extensions 1 → U(1) → G̃ → G → 1
    - Equivalently: projective representations of G
    - Physically: non-linearizable twists in quantization (rank > 1)

  For finite groups, H²(G, U(1)) ≅ H²(G, ℂ*) is the Schur multiplier.

  The Schur multiplier M(G) = H₂(G, ℤ) has a well-known structure:
""")

    # Compute H₂ (Schur multiplier) for our groups
    # For finite subgroups of SU(2):
    # - Cyclic Z_n: M(Z_n) = 0
    # - Dic_N (generalized quaternion Q_{4N}): M(Dic_N) = Z_2 for N ≥ 2
    # - 2T: M(2T) = 0
    # - 2O: M(2O) = Z_2
    # - 2I: M(2I) = Z_2
    # Reference: Karpilovsky, "The Schur Multiplier" (1987)

    schur_data = [
        ("Z₂", 2, "0", "trivial (cyclic)"),
        ("Z₆", 6, "0", "trivial (cyclic)"),
        ("Dic₁ (Z₄)", 4, "0", "trivial (cyclic)"),
        ("Dic₂ (Q₈)", 8, "0", "trivial (Q₈ is special)"),
        ("Dic₃", 12, "Z₂", "one projective class"),
        ("Dic₅", 20, "Z₂", "one projective class"),
        ("2T", 24, "0", "trivial (perfect double cover)"),
        ("2O", 48, "Z₂", "one projective class"),
        ("2I", 120, "Z₂", "one projective class"),
    ]

    print(f"  {'Group':>12}  {'|G|':>4}  {'M(G)':>6}  {'Note':>30}")
    print(f"  {'─'*58}")
    for name, order, schur, note in schur_data:
        print(f"  {name:>12}  {order:4d}  {schur:>6}  {note:>30}")

    print("""
  INTERPRETATION:
    M(G) = 0 means: every projective representation lifts to a true
    representation. No "new" bundle sectors beyond the linear ones.

    M(G) = Z₂ means: there exists ONE nontrivial projective class.
    This corresponds to a rank-2 vector bundle sector where the
    fiber carries a spinorial representation of 2H.

  KEY INSIGHT:
    Spinorial content of V_j|_{2H} is carried by higher-dimensional
    irreps of 2H (e.g., H₁, H₂ of dim 2). These irreps cannot be
    reduced to 1D characters — spinorial states are accessible only
    through vector bundle quantization, never through scalar sectors.

    For SO(3)/O:
      - H¹(2O, U(1)) = Z₂: 2 scalar sectors (both tensorial)
      - M(2O) = Z₂: 1 projective class → vector bundle sector
      - The spinorial states live in the vector bundle sector H₁

    This was already seen in script 14:
      H₁ bundle: j = 1/2, 7/2, 9/2, 11/2, 13/2 (rank-2 sections)
""")

    # ============================================================
    # PART D: WHERE DO THE SPINORIAL STATES GO?
    # ============================================================
    print("=" * 70)
    print("PART D: WHERE DO THE SPINORIAL STATES GO?")
    print("=" * 70)

    print("""
  For SO(3)/O (binary octahedral group, |2O|=48):

  The rigid rotor spectrum V_j|_{2O} decomposes into irreps of 2O.
  2O has 8 irreps: A₀, A₁ (dim 1), E (dim 2), T₀, T₁ (dim 3),
                   H₀, H₁ (dim 2), W (dim 4).

  1D irreps (scalar sectors): A₀, A₁ — both have χ(-1)=+1 (tensorial)
  2D irreps (bundle sectors): E (tensorial), H₀, H₁ (spinorial)

  The spinorial states appear as:
    - Sections of the H₁ vector bundle (rank 2) over SO(3)/O
    - These are NOT scalar wave functions but spinor-valued
    - They carry the spinorial representation of 2O

  Spectral content comparison (j ≤ 6.5):
""")

    def chi_su2(j, trace):
        d = int(2 * j + 1)
        if abs(trace - 2) < 1e-10:
            return float(d)
        if abs(trace + 2) < 1e-10:
            return float(d * ((-1) ** int(round(2 * j))))
        ha = np.arccos(np.clip(trace / 2, -1, 1))
        if abs(np.sin(ha)) < 1e-14:
            return float(d)
        return np.sin(d * ha) / np.sin(ha)

    elements = build_binary_octahedral()
    classes = compute_conjugacy_classes(elements)
    classes.sort(key=lambda c: -c['trace'])
    sizes = np.array([c['size'] for c in classes], dtype=float)
    G = int(sum(sizes))

    # Total states on SO(3) vs scalar on SO(3)/O
    total_so3 = 0
    total_scalar_O = 0
    total_all_j = 0

    comm = compute_commutator_subgroup(elements)
    comm_keys = set(comm.keys())
    abel = G // len(comm)
    class_in_comm = np.array([list(c['keys'])[0] in comm_keys for c in classes])

    print(f"  {'j':>5}  {'dim V_j':>7}  {'scalar':>7}  {'non-scalar':>10}  "
          f"{'scalar %':>8}")
    print(f"  {'─'*45}")

    for two_j in range(0, 14):
        j = two_j / 2.0
        dim = int(2 * j + 1)
        chi_Vj = np.array([chi_su2(j, c['trace']) for c in classes])

        # Total scalar content
        n_scalar = round((abel / G *
                         np.sum(sizes * chi_Vj * class_in_comm)).real)

        n_nonscalar = dim - n_scalar
        pct = 100.0 * n_scalar / dim if dim > 0 else 0

        total_so3 += dim
        total_scalar_O += n_scalar
        total_all_j += dim

        if dim > 0:
            print(f"  {j:5.1f}  {dim:7d}  {n_scalar:7d}  {n_nonscalar:10d}  "
                  f"{pct:7.1f}%")

    print(f"  {'─'*45}")
    print(f"  {'Total':>5}  {total_so3:7d}  {total_scalar_O:7d}  "
          f"{total_so3-total_scalar_O:10d}  "
          f"{100.0*total_scalar_O/total_so3:7.1f}%")

    print(f"""
  Of {total_so3} total states (j ≤ 6.5):
    {total_scalar_O} ({100*total_scalar_O/total_so3:.1f}%) are scalar (live in line bundles)
    {total_so3 - total_scalar_O} ({100*(total_so3-total_scalar_O)/total_so3:.1f}%) are non-scalar (live in vector bundles)

  The non-scalar states include:
    - Tensorial bundle states (E-type, rank 2)
    - Spinorial bundle states (H-type, rank 2)
    - Higher-rank states (T-type rank 3, W-type rank 4)

  The obstruction does not destroy spinorial content in V_j|_{{2O}}.
  Spinorial irreps (H₁, H₂, L) are intrinsically higher-dimensional
  and accessible only through vector bundle quantization.
""")

    # ============================================================
    # SUMMARY
    # ============================================================
    print("=" * 70)
    print("SUMMARY")
    print("=" * 70)
    print("""
  1. ANALYTIC PROOF (Part A):
     -1 ∈ [G,G] ⟺ no spinorial 1D char.
     Three-line proof, valid for ANY finite group.
     No ADE classification needed.

  2. COHOMOLOGICAL CLASSIFICATION (Parts B-C):
     Scalar sectors:  H¹(G, U(1)) = Ĝ_ab, |H¹| = κ
     Projective classes: H²(G, U(1)) = Schur multiplier M(G)
     The two are COMPLEMENTARY, not competing.

  3. FATE OF SPINORIAL STATES (Part D):
     Spinorial content of V_j|_{2H} survives in higher-dimensional
     irreps of 2H, accessible only through vector bundle quantization.
     The obstruction prevents 1D projection, it does not destroy states.
     On SO(3)/O: only 4.8% of states are scalar (1D) up to j=6.5.

  4. PAPER IMPLICATION:
     The three-line proof makes the obstruction theorem
     COMPLETELY ELEMENTARY. No heavy machinery needed.
     The H² connection provides conceptual depth for the discussion.
""")


if __name__ == '__main__':
    main()
