#!/usr/bin/env python3
"""
Branching rules: restriction of 2O irreps to 2D₃ ⊂ 2O.

2D₃ embedded in 2O as stabilizer of [111] body diagonal:
  a = (1+i+j+k)/2  (order 6, 120° about [111])
  b = (i-j)/√2      (order 4, 180° ⊥ [111])
Relations: a⁶ = 1, b² = a³ = -1, bab⁻¹ = a⁻¹.

RAW OUTPUT:
===========

2D₃ ⊂ 2O verified: |2D₃| = 12, all elements in 2O
Relations verified: a³ = b² = -1, bab⁻¹ = a⁻¹

Commutator subgroup [2D₃,2D₃] = ⟨a²⟩ = {1, a², a⁴}, order 3
Abelianization 2D₃/[2D₃,2D₃] ≅ Z₄, generated by image of b
  φ(b) = 1 (generator), φ(a) = 2 = φ(b²), φ(-1) = 2

2D₃ conjugacy classes (6 classes, Dic₃):
  C0: {1}           size 1, tr = +2
  C1: {a, a⁵}       size 2, tr = +1
  C2: {b, a²b, a⁴b} size 3, tr =  0
  C3: {a², a⁴}      size 2, tr = -1
  C4: {ab, a³b, a⁵b} size 3, tr = 0
  C5: {-1}           size 1, tr = -2

2D₃ character table:
           C0(1)  C1(2)  C2(3)  C3(2)  C4(3)  C5(1)
  χ₀(T)     1      1      1      1      1      1
  χ₁(S)     1     -1      i      1     -i     -1
  χ₂(T)     1      1     -1      1     -1      1
  χ₃(S)     1     -1     -i      1      i     -1
  ψ₁(S)     2      1      0     -1      0     -2     ← defining (SU2) rep
  ψ₂(T)     2     -1      0     -1      0      2

Orthogonality: all ⟨χᵢ,χⱼ⟩ = δᵢⱼ verified ✓

======================================================================
BRANCHING RULES: 2O → 2D₃ (cubic → trigonal)
======================================================================

   A₀(T) dim 1:  χ₀(T)
   A₁(T) dim 1:  χ₂(T)
    E(T) dim 2:  ψ₂(T)
   T₁(T) dim 3:  χ₀(T) ⊕ ψ₂(T)
   T₂(T) dim 3:  χ₂(T) ⊕ ψ₂(T)
   H₁(S) dim 2:  ψ₁(S)
   H₂(S) dim 2:  ψ₁(S)
    L(S) dim 4:  χ₁(S) ⊕ χ₃(S) ⊕ ψ₁(S)

======================================================================
PHYSICS SUMMARY
======================================================================

Scalar quantization sectors = 1D characters of π₁.
In cubic phase (O):  Q₈ ⊂ 2O → NO 1D spinorial chars → obstruction.
In trigonal phase (D₃): Q₈ ⊄ 2D₃ → χ₁, χ₃ are 1D spinorial → re-entrance.

Which 2O irreps produce new 1D spinorial sectors of 2D₃?
  L(S) → contains χ₁(S) (×1) and χ₃(S) (×1)

Only L (rank 4, the largest spinorial irrep) splits to produce scalar
spinorial sectors. H₁ and H₂ remain rank-2 bundles (ψ₁) — still
inaccessible to scalar quantization even in the trigonal phase.

Dimension checks:
  Σ dim²(2O)  = 1+1+4+9+9+4+4+16 = 48 = |2O| ✓
  Σ dim²(2D₃) = 1+1+1+1+4+4 = 12 = |2D₃| ✓
  Each branching preserves dimension ✓
"""

import sys
sys.path.insert(0, str(__import__('pathlib').Path(__file__).resolve().parent.parent))

import numpy as np
from src.quaternion import qmul, qconj, qkey, quat_to_su2
from src.group import build_binary_octahedral

SQ2 = np.sqrt(2)

# =============================================================
# 1. Build 2D₃ inside 2O
# =============================================================

a = np.array([0.5, 0.5, 0.5, 0.5])       # (1+i+j+k)/2
b = np.array([0.0, 1/SQ2, -1/SQ2, 0.0])   # (i-j)/√2

def generate_group(generators, max_order=200):
    elements = [np.array([1., 0., 0., 0.])]
    seen = {qkey(elements[0])}
    queue = list(elements)
    idx = 0
    while idx < len(queue):
        g = queue[idx]; idx += 1
        for gen in generators:
            for h in [qmul(g, gen), qmul(gen, g)]:
                k = qkey(h)
                if k not in seen:
                    seen.add(k)
                    queue.append(h)
                    elements.append(h)
        if len(elements) > max_order:
            raise RuntimeError(f"Group too large: {len(elements)}")
    return elements

elements_2D3 = generate_group([a, b, qconj(a)])
assert len(elements_2D3) == 12, f"|2D₃| = {len(elements_2D3)}, expected 12"

# Verify embedding in 2O
elements_2O = build_binary_octahedral()
keys_2O = {qkey(g) for g in elements_2O}
for g in elements_2D3:
    assert qkey(g) in keys_2O, f"{g} not in 2O"
print(f"2D₃ ⊂ 2O verified: |2D₃| = 12, all elements in 2O")

# Verify relations
assert np.allclose(qmul(qmul(a, a), a), [-1, 0, 0, 0]), "a³ ≠ -1"
assert np.allclose(qmul(b, b), [-1, 0, 0, 0]), "b² ≠ -1"
assert np.allclose(qmul(qmul(b, a), qconj(b)), qconj(a)), "bab⁻¹ ≠ a⁻¹"
print("Relations verified: a³ = b² = -1, bab⁻¹ = a⁻¹")

# =============================================================
# 2. Conjugacy classes of 2D₃
# =============================================================

def conjugacy_classes(elements):
    remaining = list(range(len(elements)))
    classes = []
    while remaining:
        rep_idx = remaining[0]
        rep = elements[rep_idx]
        cls, new_remaining = [], []
        for idx in remaining:
            g = elements[idx]
            is_conj = any(np.allclose(qmul(qmul(h, g), qconj(h)), rep, atol=1e-10)
                         for h in elements)
            (cls if is_conj else new_remaining).append(idx)
        classes.append(cls)
        remaining = new_remaining
    return classes

classes_2D3 = conjugacy_classes(elements_2D3)
class_sizes = [len(c) for c in classes_2D3]
assert len(classes_2D3) == 6
print(f"\n2D₃: 6 conjugacy classes, sizes = {class_sizes}")
for i, cls in enumerate(classes_2D3):
    rep = elements_2D3[cls[0]]
    print(f"  C{i}: size {len(cls)}, rep = {np.round(rep, 4)}, tr = {2*rep[0]:.4f}")

# Identify which size-3 class contains b
c_b, c_ab = None, None
for i, cls in enumerate(classes_2D3):
    if len(cls) == 3:
        for idx in cls:
            if np.allclose(elements_2D3[idx], b, atol=1e-10):
                c_b = i
            if np.allclose(elements_2D3[idx], qmul(a, b), atol=1e-10):
                c_ab = i
print(f"\n  Class with b: C{c_b}, class with ab: C{c_ab}")

# =============================================================
# 3. 2D₃ character table (textbook Dic₃)
# =============================================================
#
# Standard classes: {1}(1), {a,a⁵}(2), {a²,a⁴}(2), {-1}(1), {b,...}(3), {ab,...}(3)
# Our ordering maps to standard via:
#   C0={1}, C1={a,a⁵}, C_b={b,...}, C3={a²,a⁴}, C_ab={ab,...}, C5={-1}

# Build mapping: our class index -> standard class index
# Standard: 0={1}, 1={a,a5}, 2={a2,a4}, 3={-1}, 4={b,...}, 5={ab,...}
our_to_std = {}
for i, cls in enumerate(classes_2D3):
    size = len(cls)
    rep = elements_2D3[cls[0]]
    tr = 2 * rep[0]
    if size == 1 and tr > 0:
        our_to_std[i] = 0   # {1}
    elif size == 2 and tr > 0:
        our_to_std[i] = 1   # {a, a⁵}
    elif size == 2 and tr < 0:
        our_to_std[i] = 2   # {a², a⁴}
    elif size == 1 and tr < 0:
        our_to_std[i] = 3   # {-1}
    elif i == c_b:
        our_to_std[i] = 4   # {b, a²b, a⁴b}
    elif i == c_ab:
        our_to_std[i] = 5   # {ab, a³b, a⁵b}

# Standard character table values (indexed by standard class 0-5)
std_table = {
    'chi_0': [1, 1, 1, 1, 1, 1],
    'chi_1': [1, -1, 1, -1, 1j, -1j],
    'chi_2': [1, 1, 1, 1, -1, -1],
    'chi_3': [1, -1, 1, -1, -1j, 1j],
    'psi_1': [2, 1, -1, -2, 0, 0],
    'psi_2': [2, -1, -1, 2, 0, 0],
}

# Convert to our class ordering
CHAR_2D3 = {}
for name, std_vals in std_table.items():
    our_vals = np.array([std_vals[our_to_std[i]] for i in range(6)], dtype=complex)
    CHAR_2D3[name] = our_vals

# Verify orthogonality
print("\nOrthogonality check:")
all_ok = True
for n1 in CHAR_2D3:
    for n2 in CHAR_2D3:
        ip = sum(class_sizes[i] * np.conj(CHAR_2D3[n1][i]) * CHAR_2D3[n2][i]
                 for i in range(6)) / 12
        expected = 1 if n1 == n2 else 0
        if abs(ip - expected) > 0.01:
            print(f"  FAIL: <{n1},{n2}> = {ip}")
            all_ok = False
if all_ok:
    print("  All ⟨χᵢ,χⱼ⟩ = δᵢⱼ ✓")

# Spinorial status
print("\nSpinorial status (value at -1):")
minus1_idx = [i for i in range(6) if our_to_std[i] == 3][0]
for name in ['chi_0', 'chi_1', 'chi_2', 'chi_3', 'psi_1', 'psi_2']:
    v = CHAR_2D3[name][minus1_idx]
    if abs(v.real + 1) < 0.01 or abs(v.real + 2) < 0.01:
        status = 'SPINORIAL'
    else:
        status = 'tensorial'
    print(f"  {name}(-1) = {v:.0f}  {status}")

# =============================================================
# 4. 2O character table
# =============================================================

classes_2O = conjugacy_classes(elements_2O)
class_info_2O = []
for cls in classes_2O:
    rep = elements_2O[cls[0]]
    class_info_2O.append({
        'size': len(cls), 'trace': round(2 * rep[0], 6),
        'keys': {qkey(elements_2O[i]) for i in cls}
    })

CHAR_2O = {
    'A0': {(1,2.0):1,(12,0.0):1,(8,-1.0):1,(6,0.0):1,(1,-2.0):1,(6,-SQ2):1,(8,1.0):1,(6,SQ2):1},
    'A1': {(1,2.0):1,(12,0.0):-1,(8,-1.0):1,(6,0.0):1,(1,-2.0):1,(6,-SQ2):-1,(8,1.0):1,(6,SQ2):-1},
    'E':  {(1,2.0):2,(12,0.0):0,(8,-1.0):-1,(6,0.0):2,(1,-2.0):2,(6,-SQ2):0,(8,1.0):-1,(6,SQ2):0},
    'T1': {(1,2.0):3,(12,0.0):1,(8,-1.0):0,(6,0.0):-1,(1,-2.0):3,(6,-SQ2):-1,(8,1.0):0,(6,SQ2):-1},
    'T2': {(1,2.0):3,(12,0.0):-1,(8,-1.0):0,(6,0.0):-1,(1,-2.0):3,(6,-SQ2):1,(8,1.0):0,(6,SQ2):1},
    'H1': {(1,2.0):2,(12,0.0):0,(8,-1.0):-1,(6,0.0):0,(1,-2.0):-2,(6,-SQ2):-SQ2,(8,1.0):1,(6,SQ2):SQ2},
    'H2': {(1,2.0):2,(12,0.0):0,(8,-1.0):-1,(6,0.0):0,(1,-2.0):-2,(6,-SQ2):SQ2,(8,1.0):1,(6,SQ2):-SQ2},
    'L':  {(1,2.0):4,(12,0.0):0,(8,-1.0):1,(6,0.0):0,(1,-2.0):-4,(6,-SQ2):0,(8,1.0):-1,(6,SQ2):0},
}

def char_2O_val(irrep, q):
    k = qkey(q)
    for ci in class_info_2O:
        if k in ci['keys']:
            key = (ci['size'], round(ci['trace'], 4))
            for (s, t), v in CHAR_2O[irrep].items():
                if s == key[0] and abs(t - key[1]) < 0.01:
                    return v
    raise ValueError(f"Element {q} not found in 2O classes")

# =============================================================
# 5. Branching rules: decompose restricted 2O characters
# =============================================================

print("\n" + "=" * 70)
print("BRANCHING RULES: 2O → 2D₃ (cubic → trigonal)")
print("=" * 70)
print()

irrep_names_2O = ['A0', 'A1', 'E', 'T1', 'T2', 'H1', 'H2', 'L']
labels = {'chi_0': 'χ₀(T)', 'chi_1': 'χ₁(S)', 'chi_2': 'χ₂(T)',
          'chi_3': 'χ₃(S)', 'psi_1': 'ψ₁(S)', 'psi_2': 'ψ₂(T)'}
irrep_names_2D3 = ['chi_0', 'chi_2', 'chi_1', 'chi_3', 'psi_1', 'psi_2']

for name_2O in irrep_names_2O:
    # Restricted character on 2D₃ classes
    chi_res = np.array([char_2O_val(name_2O, elements_2D3[classes_2D3[i][0]])
                        for i in range(6)], dtype=complex)
    dim = int(chi_res[0].real)
    rho_m1 = chi_res[minus1_idx].real
    spin = 'S' if rho_m1 < 0 else 'T'

    # Decompose via character inner products
    decomp = []
    dim_check = 0
    for irr in irrep_names_2D3:
        ip = sum(class_sizes[i] * np.conj(CHAR_2D3[irr][i]) * chi_res[i]
                 for i in range(6)) / 12
        m = int(round(ip.real))
        assert abs(ip.imag) < 0.1 and abs(ip.real - m) < 0.1, \
            f"{name_2O}, {irr}: multiplicity not integer: {ip}"
        if m > 0:
            d = 2 if irr.startswith('psi') else 1
            dim_check += m * d
            decomp.append(f"{'%d' % m if m > 1 else ''}{labels[irr]}")

    assert dim_check == dim, f"{name_2O}: dim mismatch {dim_check} vs {dim}"
    decomp_str = ' ⊕ '.join(decomp)
    print(f"  {name_2O:>3}({spin}) dim {dim}:  {decomp_str}")

# =============================================================
# 6. Physics summary
# =============================================================

print()
print("=" * 70)
print("PHYSICS SUMMARY")
print("=" * 70)
print()
print("Scalar quantization sectors = 1D characters of π₁.")
print("In cubic phase (O):  Q₈ ⊂ 2O → no 1D spinorial chars → obstruction.")
print("In trigonal phase (D₃): Q₈ ⊄ 2D₃ → χ₁, χ₃ are 1D spinorial → re-entrance.")
print()
print("Which 2O irreps produce new 1D spinorial sectors of 2D₃?")
for name_2O in irrep_names_2O:
    chi_res = np.array([char_2O_val(name_2O, elements_2D3[classes_2D3[i][0]])
                        for i in range(6)], dtype=complex)
    for irr in ['chi_1', 'chi_3']:
        ip = sum(class_sizes[i] * np.conj(CHAR_2D3[irr][i]) * chi_res[i]
                 for i in range(6)) / 12
        m = int(round(ip.real))
        if m > 0:
            print(f"  {name_2O} → contains {labels[irr]} (×{m})")

print()
print("Only L (rank 4, largest spinorial irrep) splits to produce scalar")
print("spinorial sectors. H₁ and H₂ remain rank-2 (ψ₁) — still inaccessible")
print("to scalar quantization even in the trigonal phase.")

# Dimension checks
dim_sq_2O = sum(int(list(CHAR_2O[n].values())[0])**2 for n in irrep_names_2O)
print(f"\nDimension checks:")
print(f"  Σ dim²(2O)  = {dim_sq_2O} = |2O| = 48 {'✓' if dim_sq_2O == 48 else '✗'}")
print(f"  Σ dim²(2D₃) = {1+1+1+1+4+4} = |2D₃| = 12 {'✓' if 1+1+1+1+4+4 == 12 else '✗'}")
