#!/usr/bin/env python3
"""
Script 54: Re-entrance duality structure in D_n (n odd).

For D_n (n odd), the group is non-obstructed (Q₈ ⊄ 2D_n).
Abel(2D_n) ≅ Z₄ → 4 scalar characters: 2 tensorial (χ₀, χ₁) + 2 spinorial (χ₂, χ₃).

Key finding: duality is a SECTOR property, not a group property.
  - Tensorial duality FAILS: m(χ,j) + m(χ,j*-j) ∈ {0, 2} (not 1)
  - Spinorial duality HOLDS: m(χ,j) + m(χ,j*-j) = 1 (binary occupation)
  - Spinorial periodicity: m(j+P) = m(j) + 1 (clean, as in obstructed case)

Mechanism: the only SO(3) elements that fail condition (B) in D_n (n odd)
have order d=2. These have half-angle π/2 (trace = 0). At half-integer j,
χ_j(trace=0) = sin((2j+1)π/2) = sin(even·π/2) = 0. So d=2 modes are
INVISIBLE to spinorial characters. Remaining elements all satisfy (B),
hence mode antisymmetry and duality hold in the spinorial sector.

Groups tested: D₃, D₅, D₇, D₉, D₁₁.

References: main_v5.tex Corollary 3.5, Lemma 3.4 (mode antisymmetry).
Tracker: item 0h (re-entrance duality structure in D₃).

Run: /usr/bin/python3 -m pytest tests/54_reentrance_D_odd.py -v
Date: Feb 2026

RAW OUTPUT (81 passed, 0.64s):
  TestNonObstruction::test_minus_one_not_in_commutator[3,5,7,9,11] 5 PASSED
  TestNonObstruction::test_abelianization_is_Z4[3,5,7,9,11] 5 PASSED
  TestNonObstruction::test_four_scalar_characters[3,5,7,9,11] 5 PASSED
  TestTensorialDualityFails::test_sum_is_0_or_2_chi0[3,5,7,9,11] 5 PASSED
  TestTensorialDualityFails::test_sum_is_0_or_2_chi1[3,5,7,9,11] 5 PASSED
  TestTensorialDualityFails::test_converse_formula_chi0[3,5,7,9,11] 5 PASSED
  TestTensorialDualityFails::test_chi0_chi1_complementary[3,5,7,9,11] 5 PASSED
  TestSpinorialDualityHolds::test_binary_occupation[3,5,7,9,11] 5 PASSED
  TestSpinorialDualityHolds::test_duality_sum_equals_1_chi2[3,5,7,9,11] 5 PASSED
  TestSpinorialDualityHolds::test_duality_sum_equals_1_chi3[3,5,7,9,11] 5 PASSED
  TestSpinorialDualityHolds::test_chi2_equals_chi3[3,5,7,9,11] 5 PASSED
  TestSpinorialDualityHolds::test_half_filling[3,5,7,9,11] 5 PASSED
  TestSpinorialPeriodicity::test_periodicity_chi2[3,5,7,9,11] 5 PASSED
  TestD2ModeVanishing::test_chi_j_at_trace_zero PASSED
  TestD2ModeVanishing::test_only_d2_fails_condition_B[3,5,7,9,11] 5 PASSED
  TestHardcodedRegression::test_hardcoded_spinorial_values[3,5,7,9,11] 5 PASSED
  TestHardcodedRegression::test_pattern_first_half_zero_second_half_one[3,5,7,9,11] 5 PASSED
"""
import sys
sys.path.insert(0, '/Users/alextoader/Sites/st_spinorial_obstruction')

import numpy as np
import pytest
from src.quaternion import qkey, qmul
from src.group import compute_conjugacy_classes, compute_commutator_subgroup


def chi_su2(j, trace):
    """SU(2) spin-j character at given trace = 2*cos(alpha)."""
    d = int(2 * j + 1)
    if abs(trace - 2) < 1e-10:
        return float(d)
    if abs(trace + 2) < 1e-10:
        return float(d * ((-1) ** int(round(2 * j))))
    ha = np.arccos(np.clip(trace / 2, -1, 1))
    if abs(np.sin(ha)) < 1e-14:
        return float(d)
    return np.sin(d * ha) / np.sin(ha)


def build_binary_dihedral(n):
    """2D_n = Dic_n in SU(2). Order 4n.
    Generated by a = e^{iπ/n} and x = j, with:
      a^{2n} = 1, x² = a^n = -1, xax⁻¹ = a⁻¹
    """
    j_quat = np.array([0.0, 0.0, 1.0, 0.0])
    result = []
    for k in range(2 * n):
        theta = k * np.pi / n
        q = np.array([np.cos(theta), 0, 0, np.sin(theta)])
        result.append(q)
        result.append(qmul(j_quat, q))
    return np.array(result)


def build_characters(n, elements, classes):
    """Build the 4 characters of Z₄ = 2D_n / [2D_n, 2D_n] for n odd.

    χ₀: a→+1, x→+1   (tensorial)
    χ₁: a→+1, x→-1   (tensorial)
    χ₂: a→-1, x→+i   (spinorial)
    χ₃: a→-1, x→-i   (spinorial)
    """
    a_powers = {}
    for k in range(2 * n):
        angle = k * np.pi / n
        a_powers[k] = np.array([np.cos(angle), 0, 0, np.sin(angle)])

    x_elem = np.array([0, 0, 1, 0], dtype=float)
    xa_powers = {}
    for k in range(2 * n):
        xa_powers[k] = qmul(x_elem, a_powers[k])

    char_defs = {
        'chi0': (1.0, 1.0 + 0j),
        'chi1': (1.0, -1.0 + 0j),
        'chi2': (-1.0, 1j),
        'chi3': (-1.0, -1j),
    }

    chars = {}
    for cname, (chi_a, chi_x) in char_defs.items():
        elem_vals = {}
        for k in range(2 * n):
            elem_vals[qkey(a_powers[k])] = chi_a ** k
        for k in range(2 * n):
            elem_vals[qkey(xa_powers[k])] = chi_x * (chi_a ** k)
        chi_on_classes = []
        for c in classes:
            rep_key = list(c['keys'])[0]
            chi_on_classes.append(elem_vals[rep_key])
        chars[cname] = np.array(chi_on_classes)

    return chars


def prepare_group(n):
    """Build complete group data for D_n (n odd)."""
    elements = build_binary_dihedral(n)
    G_order = len(elements)      # 4n
    H_order = 2 * n              # |H| = 2n
    j_star = H_order // 2 - 1    # n - 1
    P = H_order // 2             # n

    classes = compute_conjugacy_classes(elements)
    classes.sort(key=lambda c: -c['trace'])
    sizes = np.array([c['size'] for c in classes], dtype=float)

    chars = build_characters(n, elements, classes)

    return {
        'n': n, 'name': f'D_{n}',
        'G': G_order, 'H': H_order,
        'j_star': j_star, 'P': P,
        'classes': classes, 'sizes': sizes,
        'chars': chars, 'elements': elements,
    }


def m_chi(j, grp, chi_name):
    """Multiplicity of character chi_name in spin-j rep."""
    chi_Vj = np.array([chi_su2(j, c['trace']) for c in grp['classes']])
    m = np.sum(grp['chars'][chi_name].conj() * chi_Vj * grp['sizes']) / grp['G']
    return int(round(m.real))


# ============================================================
# Hardcoded sub-threshold spinorial values for regression.
# m(χ₂, j) for half-integer j in [1/2, j*-1/2].
# χ₃ values are identical (conjugate characters).
# ============================================================

# D₃: j*=2, half-int sub-threshold = {0.5, 1.5}
SUB_D3_SPIN = {0.5: 0, 1.5: 1}

# D₅: j*=4, half-int sub-threshold = {0.5, 1.5, 2.5, 3.5}
SUB_D5_SPIN = {0.5: 0, 1.5: 0, 2.5: 1, 3.5: 1}

# D₇: j*=6, half-int sub-threshold = {0.5, ..., 5.5}
SUB_D7_SPIN = {0.5: 0, 1.5: 0, 2.5: 0, 3.5: 1, 4.5: 1, 5.5: 1}

# D₉: j*=8, half-int sub-threshold = {0.5, ..., 7.5}
SUB_D9_SPIN = {0.5: 0, 1.5: 0, 2.5: 0, 3.5: 0, 4.5: 1, 5.5: 1, 6.5: 1, 7.5: 1}

# D₁₁: j*=10, half-int sub-threshold = {0.5, ..., 9.5}
SUB_D11_SPIN = {0.5: 0, 1.5: 0, 2.5: 0, 3.5: 0, 4.5: 0,
                5.5: 1, 6.5: 1, 7.5: 1, 8.5: 1, 9.5: 1}


# ============================================================
# Test classes
# ============================================================

class TestNonObstruction:
    """Verify D_n (n odd) is non-obstructed: -1 ∉ [G,G]."""

    @pytest.fixture(params=[3, 5, 7, 9, 11], scope='class')
    def grp(self, request):
        return prepare_group(request.param)

    def test_minus_one_not_in_commutator(self, grp):
        comm = compute_commutator_subgroup(grp['elements'])
        mk = qkey(np.array([-1, 0, 0, 0], dtype=float))
        assert mk not in comm

    def test_abelianization_is_Z4(self, grp):
        comm = compute_commutator_subgroup(grp['elements'])
        assert grp['G'] // len(comm) == 4

    def test_four_scalar_characters(self, grp):
        """Four characters, orthonormal."""
        names = ['chi0', 'chi1', 'chi2', 'chi3']
        for i, n1 in enumerate(names):
            for j, n2 in enumerate(names):
                inner = np.sum(grp['chars'][n1].conj() * grp['chars'][n2]
                               * grp['sizes']) / grp['G']
                expected = 1.0 if i == j else 0.0
                assert abs(inner - expected) < 1e-10


class TestTensorialDualityFails:
    """Tensorial characters: duality sums are 0 or 2, never 1."""

    @pytest.fixture(params=[3, 5, 7, 9, 11], scope='class')
    def grp(self, request):
        return prepare_group(request.param)

    def test_sum_is_0_or_2_chi0(self, grp):
        j_star = grp['j_star']
        for j in range(j_star + 1):
            jd = j_star - j
            if jd < j:
                break
            s = m_chi(j, grp, 'chi0') + m_chi(jd, grp, 'chi0')
            assert s in (0, 2), f"D_{grp['n']}: m(chi0,{j})+m(chi0,{jd})={s}"

    def test_sum_is_0_or_2_chi1(self, grp):
        j_star = grp['j_star']
        for j in range(j_star + 1):
            jd = j_star - j
            if jd < j:
                break
            s = m_chi(j, grp, 'chi1') + m_chi(jd, grp, 'chi1')
            assert s in (0, 2), f"D_{grp['n']}: m(chi1,{j})+m(chi1,{jd})={s}"

    def test_converse_formula_chi0(self, grp):
        """m(χ₀, 0) + m(χ₀, j*) = 2 (both endpoints filled)."""
        m0 = m_chi(0, grp, 'chi0')
        mj = m_chi(grp['j_star'], grp, 'chi0')
        assert m0 == 1 and mj == 1
        assert m0 + mj == 2

    def test_chi0_chi1_complementary(self, grp):
        """At each sub-threshold j, exactly one of χ₀, χ₁ is filled.

        Proof: m(χ₀)+m(χ₁) = #{weights m ∈ [-j,j] with n|m} for the
        rotation subgroup C_n. For j ≤ n-1, only m=0 qualifies, giving
        total = 1. The reflection acts by ±1 on this 1D invariant space,
        assigning it to χ₀ or χ₁ exclusively.
        """
        j_star = grp['j_star']
        for j in range(j_star + 1):
            m0 = m_chi(j, grp, 'chi0')
            m1 = m_chi(j, grp, 'chi1')
            assert m0 + m1 == 1, f"D_{grp['n']} j={j}: chi0+chi1={m0+m1}"


class TestSpinorialDualityHolds:
    """Spinorial characters: binary duality m(j)+m(j*-j)=1."""

    @pytest.fixture(params=[3, 5, 7, 9, 11], scope='class')
    def grp(self, request):
        return prepare_group(request.param)

    def test_binary_occupation(self, grp):
        """m(χ₂, j) ∈ {0, 1} for j in [1/2, j*-1/2]."""
        j_star = grp['j_star']
        for two_j in range(1, 2 * j_star, 2):
            j = two_j / 2.0
            m = m_chi(j, grp, 'chi2')
            assert m in (0, 1), f"D_{grp['n']} j={j}: m(chi2)={m}"

    def test_duality_sum_equals_1_chi2(self, grp):
        """m(χ₂, j) + m(χ₂, j*-j) = 1 for all valid pairs."""
        j_star = grp['j_star']
        for two_j in range(1, 2 * j_star, 2):
            j = two_j / 2.0
            jd = j_star - j
            if jd <= 0:
                break
            s = m_chi(j, grp, 'chi2') + m_chi(jd, grp, 'chi2')
            assert s == 1, f"D_{grp['n']}: m(chi2,{j})+m(chi2,{jd})={s}"

    def test_duality_sum_equals_1_chi3(self, grp):
        """m(χ₃, j) + m(χ₃, j*-j) = 1 for all valid pairs."""
        j_star = grp['j_star']
        for two_j in range(1, 2 * j_star, 2):
            j = two_j / 2.0
            jd = j_star - j
            if jd <= 0:
                break
            s = m_chi(j, grp, 'chi3') + m_chi(jd, grp, 'chi3')
            assert s == 1, f"D_{grp['n']}: m(chi3,{j})+m(chi3,{jd})={s}"

    def test_chi2_equals_chi3(self, grp):
        """Conjugate characters have identical multiplicities."""
        for two_j in range(1, 4 * grp['j_star'], 2):
            j = two_j / 2.0
            m2 = m_chi(j, grp, 'chi2')
            m3 = m_chi(j, grp, 'chi3')
            assert m2 == m3, f"D_{grp['n']} j={j}: chi2={m2} != chi3={m3}"

    def test_half_filling(self, grp):
        """Exactly half of sub-threshold levels are filled (follows from duality)."""
        j_star = grp['j_star']
        # Half-integers in (0, j*): 1/2, 3/2, ..., j*-1/2. Count = j* = n-1.
        sub_count = sum(m_chi(two_j / 2.0, grp, 'chi2')
                        for two_j in range(1, 2 * j_star, 2))
        n_sub = len(range(1, 2 * j_star, 2))
        assert sub_count * 2 == n_sub, (
            f"D_{grp['n']}: filled={sub_count}, total={n_sub}, "
            f"expected half-filling")


class TestSpinorialPeriodicity:
    """Spinorial periodicity: m(j+P) = m(j) + 1 at half-integer j."""

    @pytest.fixture(params=[3, 5, 7, 9, 11], scope='class')
    def grp(self, request):
        return prepare_group(request.param)

    def test_periodicity_chi2(self, grp):
        P = grp['P']
        for two_j in range(1, 8 * P, 2):
            j = two_j / 2.0
            jp = j + P
            m_j = m_chi(j, grp, 'chi2')
            m_jp = m_chi(jp, grp, 'chi2')
            assert m_jp == m_j + 1, (
                f"D_{grp['n']}: m(chi2,{jp}) = {m_jp} != m(chi2,{j})+1 = {m_j+1}")


class TestD2ModeVanishing:
    """The d=2 mode vanishes at all half-integer j (the mechanism)."""

    def test_chi_j_at_trace_zero(self):
        """χ_j(trace=0) = 0 for all half-integer j."""
        for two_j in range(1, 40, 2):
            j = two_j / 2.0
            val = chi_su2(j, 0.0)
            assert abs(val) < 1e-10, f"j={j}: chi_j(trace=0) = {val}"

    @pytest.fixture(params=[3, 5, 7, 9, 11], scope='class')
    def grp(self, request):
        return prepare_group(request.param)

    def test_only_d2_fails_condition_B(self, grp):
        """In D_n (n odd), only order-2 SO(3) elements fail condition (B)."""
        elements = grp['elements']
        H = grp['H']
        seen = set()
        for q in elements:
            k = qkey(q)
            neg_k = qkey(-q)
            if neg_k in seen:
                continue
            seen.add(k)
            # abs(q[0]) folds half-angle to [0, π/2]: q and -q give the
            # same SO(3) rotation, so the SO(3) order is determined by
            # the folded half-angle.
            cos_ha = abs(q[0])
            if cos_ha > 1 - 1e-12:
                continue
            ha = np.arccos(np.clip(cos_ha, -1, 1))
            for d in range(1, 200):
                if abs(d * ha / np.pi - round(d * ha / np.pi)) < 1e-8:
                    break
            assert H % d == 0, f"d={d} does not divide |H|={H}"
            ratio = H // d
            if ratio % 2 == 1:
                assert d == 2, (
                    f"D_{grp['n']}: element with SO(3) order {d} fails (B), "
                    f"|H|/d = {ratio}")


class TestHardcodedRegression:
    """Pin sub-threshold spinorial values against hardcoded tables."""

    TABLES = {
        3: SUB_D3_SPIN,
        5: SUB_D5_SPIN,
        7: SUB_D7_SPIN,
        9: SUB_D9_SPIN,
        11: SUB_D11_SPIN,
    }

    @pytest.fixture(params=[3, 5, 7, 9, 11], scope='class')
    def grp(self, request):
        return prepare_group(request.param)

    def test_hardcoded_spinorial_values(self, grp):
        table = self.TABLES[grp['n']]
        for j, expected in table.items():
            m = m_chi(j, grp, 'chi2')
            assert m == expected, (
                f"D_{grp['n']} j={j}: m(chi2) = {m}, expected {expected}")

    def test_pattern_first_half_zero_second_half_one(self, grp):
        """Sub-threshold: first (n-1)/2 levels empty, last (n-1)/2 filled.

        Observed for all tested n. With binary occupation and duality,
        this follows if m(χ₂, j) is monotone non-decreasing — verified
        empirically for D₃ through D₁₁.
        """
        n = grp['n']
        j_star = grp['j_star']
        # Half-integers: 1/2, 3/2, ..., j*-1/2. Count = j* = n-1.
        mults = [m_chi(two_j / 2.0, grp, 'chi2')
                 for two_j in range(1, 2 * j_star, 2)]
        # First half should be 0, second half should be 1
        mid = len(mults) // 2
        assert all(m == 0 for m in mults[:mid]), (
            f"D_{grp['n']}: first half not all zero: {mults[:mid]}")
        assert all(m == 1 for m in mults[mid:]), (
            f"D_{grp['n']}: second half not all one: {mults[mid:]}")


if __name__ == '__main__':
    pytest.main([__file__, '-v', '-s'])
