#!/usr/bin/env python3
"""
Branching rules: restriction of 2I irreps to 2D₅ ⊂ 2I.

2D₅ = Dic₅ (dicyclic of order 20) embedded in 2I as stabilizer
of a pentagonal axis:
  a ∈ 2I with trace = φ = (1+√5)/2  (order 10, C₅ rotation)
  b = i ∈ 2I                         (order 4, C₂ ⊥ to C₅)
Relations: a⁵ = b² = -1, bab⁻¹ = a⁻¹.

RAW OUTPUT:
===========

2I ⊂ SU(2) verified: |2I| = 120, 9 conjugacy classes
2D₅ ⊂ 2I verified: |2D₅| = 20, all elements in 2I
Relations verified: a⁵ = b² = -1, bab⁻¹ = a⁻¹

Commutator subgroup [2D₅,2D₅] = ⟨a²⟩, order 5
Abelianization 2D₅/[2D₅,2D₅] ≅ Z₄, generated by image of b
  φ(b) = 1 (generator), φ(a) = 2, φ(-1) = 2

2D₅ conjugacy classes (8 classes, Dic₅):
  C0: {1}           size 1, tr = +2
  C1: {a, a⁹}       size 2, tr = +φ ≈ +1.618
  C2: {a², a⁸}      size 2, tr = +φ⁻¹ ≈ +0.618
  C3: {a³, a⁷}      size 2, tr = -φ⁻¹ ≈ -0.618
  C4: {a⁴, a⁶}      size 2, tr = -φ ≈ -1.618
  C5: {-1}           size 1, tr = -2
  C6: {b, a²b, a⁴b, a⁶b, a⁸b}   size 5, tr = 0
  C7: {ab, a³b, a⁵b, a⁷b, a⁹b}  size 5, tr = 0

2D₅ character table:
           C0(1)  C1(2)   C2(2)    C3(2)   C4(2)  C5(1)  C6(5)  C7(5)
  χ₀(T)     1      1       1        1       1       1      1      1
  χ₁(S)     1     -1       1       -1       1      -1      i     -i
  χ₂(T)     1      1       1        1       1       1     -1     -1
  χ₃(S)     1     -1       1       -1       1      -1     -i      i
  ψ₁(S)     2      φ      φ⁻¹     -φ⁻¹    -φ      -2      0      0
  ψ₂(T)     2     φ⁻¹    -φ       -φ      φ⁻¹      2      0      0
  ψ₃(S)     2    -φ⁻¹    -φ        φ      φ⁻¹     -2      0      0
  ψ₄(T)     2     -φ      φ⁻¹     φ⁻¹     -φ       2      0      0

Spinorial: χ₁, χ₃ (1D, χ(-1)=-1) and ψ₁, ψ₃ (2D, χ(-1)=-2).
Tensorial: χ₀, χ₂ (1D, χ(-1)=+1) and ψ₂, ψ₄ (2D, χ(-1)=+2).

Orthogonality: all ⟨χᵢ,χⱼ⟩ = δᵢⱼ verified ✓
Sum dim² = 4×1 + 4×4 = 20 = |2D₅| ✓

2I character table (9 irreps):
   A(T)  dim 1: trivial (j=0)
   T(T)  dim 3: j=1
  T'(T)  dim 3: conjugate of T (swap φ ↔ -φ⁻¹ in size-12 classes)
   G(T)  dim 4: from I ≅ A₅ (tensorial)
   H(T)  dim 5: j=2
  F₁(S)  dim 2: j=1/2 (defining rep)
  F₂(S)  dim 2: conjugate of F₁ (swap φ ↔ -φ⁻¹)
  G'(S)  dim 4: j=3/2
   D(S)  dim 6: j=5/2

Sum dim² = 1+9+9+16+25+4+4+16+36 = 120 = |2I| ✓

======================================================================
BRANCHING RULES: 2I → 2D₅ (icosahedral → pentagonal)
======================================================================

TENSORIAL:
    A(T) dim 1:  χ₀(T)
    T(T) dim 3:  χ₂(T) ⊕ ψ₂(T)
   T'(T) dim 3:  χ₂(T) ⊕ ψ₄(T)
    G(T) dim 4:  ψ₂(T) ⊕ ψ₄(T)
    H(T) dim 5:  χ₀(T) ⊕ ψ₂(T) ⊕ ψ₄(T)

SPINORIAL:
   F₁(S) dim 2:  ψ₁(S)
   F₂(S) dim 2:  ψ₃(S)
   G'(S) dim 4:  ψ₁(S) ⊕ ψ₃(S)
    D(S) dim 6:  χ₁(S) ⊕ χ₃(S) ⊕ ψ₁(S) ⊕ ψ₃(S)

All dimension checks pass ✓.

======================================================================
PHYSICS SUMMARY
======================================================================

Scalar quantization sectors = 1D characters of π₁.
In icosahedral phase (I): Q₈ ⊂ 2I → NO 1D spinorial chars → obstruction.
In pentagonal phase (D₅): Q₈ ⊄ 2D₅ → χ₁, χ₃ are 1D spinorial → re-entrance.

Which 2I irreps produce new 1D spinorial sectors of 2D₅?
  D(S) dim 6 → contains χ₁(S) (×1) and χ₃(S) (×1)

Only D (rank 6, the largest spinorial irrep of 2I) splits to produce
scalar spinorial sectors. F₁, F₂ remain rank-2 (ψ₁, ψ₃ respectively).
G' remains rank-2 per component (ψ₁ ⊕ ψ₃). None of these are
accessible to scalar quantization.

Pattern across all three polyhedral groups:
  2O: only L (rank 4 = max spinorial rank) → χ₁, χ₃ of 2D₃
  2T: all Fₖ (rank 2 = max spinorial rank) → χ₁, χ₃, χ₅ of Z₆
  2I: only D (rank 6 = max spinorial rank) → χ₁, χ₃ of 2D₅

Restoration comes exclusively from the highest-rank spinorial irrep(s).

Dimension checks:
  Σ dim²(2I)  = 120 = |2I|  ✓
  Σ dim²(2D₅) = 20  = |2D₅| ✓
  Each branching preserves dimension ✓

======================================================================
CHALLENGES / POTENTIAL ISSUES
======================================================================

1. The 2I character table requires identifying 9 irreps. The first 6
   come directly from SU(2) spin-j representations (j=0,...,5/2), all
   irreducible when restricted to 2I. The remaining 3 (T', F₂, G)
   are obtained as:
     T' = conjugate of T (swap φ ↔ -φ⁻¹ in the golden-ratio classes)
     F₂ = conjugate of F₁ (same swap)
     G  = 4D tensorial irrep from I ≅ A₅, character [4,-1,-1,-1,-1,1,1,0,4]
   All verified by full orthonormality check.

2. The choice of C₅ axis determines which D₅ subgroup (hence which 2D₅).
   Different C₅ axes give conjugate subgroups with identical branching.
   The icosahedron has 6 such axes.

3. F₁ and F₂ are conjugate 2D irreps of 2I, mapping to different 2D
   irreps of 2D₅ (ψ₁ vs ψ₃). This reflects the Z₄ abelianization:
   ψ₁ and ψ₃ are related by tensoring with χ₂.

4. The 4D tensorial irrep G of 2I has character [4,-1,-1,-1,-1,1,1,0,4].
   This is NOT the j=3/2 representation (which is G', spinorial with
   chi(-1)=-4). G comes from the 4D irrep of I ≅ A₅ lifted to 2I.

5. For physical transitions I → D₅, the D₅ must be a point group
   subgroup of I. The icosahedral group I has D₅ as a maximal subgroup
   (stabilizer of a pentagonal face). This is the unique pentagonal
   distortion pathway.
"""

import sys
sys.path.insert(0, '/Users/alextoader/Sites/st_spinorial_obstruction')

import numpy as np
from src.quaternion import qmul, qconj, qkey, qinv
from src.group import build_binary_icosahedral, compute_conjugacy_classes

phi = (1.0 + np.sqrt(5.0)) / 2.0
inv_phi = phi - 1.0

# =============================================================
# 1. Build 2I and its conjugacy classes
# =============================================================

elements_2I = build_binary_icosahedral()
assert len(elements_2I) == 120
keys_2I = {qkey(e) for e in elements_2I}

classes_2I = compute_conjugacy_classes(elements_2I)
classes_2I.sort(key=lambda c: -c['trace'])
assert len(classes_2I) == 9
print(f"2I: |2I| = 120, 9 conjugacy classes")
for i, c in enumerate(classes_2I):
    print(f"  C{i}: size {c['size']}, trace = {c['trace']:.6f}")

# =============================================================
# 2. 2I character table
# =============================================================

sorted_traces = [c['trace'] for c in classes_2I]
sorted_sizes = np.array([c['size'] for c in classes_2I])


def chi_j(j, trace):
    """SU(2) spin-j character at element with given SU(2) trace."""
    if abs(trace - 2) < 1e-10:
        return float(int(2 * j + 1))
    if abs(trace + 2) < 1e-10:
        return float(int(2 * j + 1) * ((-1) ** (int(round(2 * j)))))
    ha = np.arccos(np.clip(trace / 2, -1, 1))
    d = np.sin(ha)
    if abs(d) < 1e-14:
        return float(int(2 * j + 1))
    return np.sin((2 * j + 1) * ha) / d


# 6 irreps from SU(2) j=0,...,5/2
irreps_2I = {}
for name, j in [('A', 0), ('F1', 0.5), ('T', 1), ('Gp', 1.5), ('H', 2), ('D', 2.5)]:
    irreps_2I[name] = np.array([chi_j(j, t) for t in sorted_traces])

# 3 remaining irreps: T', F2, G
# Defined by character values on classes sorted by trace (descending):
# Traces: 2, phi, 1, inv_phi, 0, -inv_phi, -1, -phi, -2
# T' = conjugate of T (swap phi <-> -inv_phi in golden-ratio classes)
# F2 = conjugate of F1 (same swap)
# G = 4D tensorial from I ≅ A₅

# Map trace -> sorted class index by proximity
def trace_to_idx(trace_val):
    dists = [abs(t - trace_val) for t in sorted_traces]
    return int(np.argmin(dists))

# Character values keyed by reference traces
ref_traces = [2.0, phi, inv_phi, -inv_phi, -phi, 1.0, -1.0, 0.0, -2.0]

Tp_ref = [3, -inv_phi, phi, phi, -inv_phi, 0, 0, -1, 3]
F2_ref = [2, -inv_phi, -phi, phi, inv_phi, 1, -1, 0, -2]
G_ref = [4, -1, -1, -1, -1, 1, 1, 0, 4]

for name, ref_vals in [('Tp', Tp_ref), ('F2', F2_ref), ('G', G_ref)]:
    vals = np.zeros(9)
    for rt, rv in zip(ref_traces, ref_vals):
        vals[trace_to_idx(rt)] = rv
    irreps_2I[name] = vals

# Verify orthonormality
print("\nOrthogonality check (2I):")
names_2I = ['A', 'F1', 'F2', 'T', 'Tp', 'G', 'Gp', 'H', 'D']
all_ok = True
for n1 in names_2I:
    for n2 in names_2I:
        ip = np.sum(sorted_sizes * irreps_2I[n1] * irreps_2I[n2]) / 120
        expected = 1 if n1 == n2 else 0
        if abs(ip - expected) > 0.01:
            print(f"  FAIL: <{n1},{n2}> = {ip:.4f}")
            all_ok = False
if all_ok:
    print("  All ⟨Γᵢ,Γⱼ⟩ = δᵢⱼ ✓")

dim_sq = sum(int(irreps_2I[n][0]) ** 2 for n in names_2I)
print(f"  Σ dim² = {dim_sq} (should be 120)")

# Spinorial status
spin_2I = {}
minus1_2I = [i for i, c in enumerate(classes_2I) if c['size'] == 1 and c['trace'] < 0][0]
for name in names_2I:
    spin_2I[name] = 'S' if irreps_2I[name][minus1_2I] < 0 else 'T'

print("\nSpinorial status (2I):")
for name in names_2I:
    dim = int(irreps_2I[name][0])
    print(f"  {name:>3}({spin_2I[name]}): dim {dim}, χ(-1) = {irreps_2I[name][minus1_2I]:+.0f}")

# =============================================================
# 3. Build 2D₅ inside 2I
# =============================================================

# Generator a: order 10, trace = phi
a = None
for e in elements_2I:
    if abs(2 * e[0] - phi) < 0.001:
        a = e
        break
assert a is not None

# Generator b: order 4, trace = 0, bab^{-1} = a^{-1}
b = None
for e in elements_2I:
    if abs(e[0]) < 0.001 and abs(e[1] - 1) < 0.001 and abs(e[2]) < 0.001:
        b = e
        break
assert b is not None

# Verify relations
a5 = a.copy()
for _ in range(4):
    a5 = qmul(a5, a)
assert np.allclose(a5, [-1, 0, 0, 0], atol=1e-10), "a⁵ ≠ -1"
assert np.allclose(qmul(b, b), [-1, 0, 0, 0], atol=1e-10), "b² ≠ -1"
assert np.allclose(qmul(qmul(b, a), qinv(b)), qinv(a), atol=1e-10), "bab⁻¹ ≠ a⁻¹"
print(f"\n2D₅ generators: a (trace = {2*a[0]:.4f}), b = i")
print("Relations verified: a⁵ = b² = -1, bab⁻¹ = a⁻¹")

# Powers of a (exact elements from 2I)
identity = None
for e in elements_2I:
    if abs(e[0] - 1) < 0.001 and np.sum(e[1:] ** 2) < 0.001:
        identity = e
        break

powers = [identity]
curr = a.copy()
for k in range(1, 10):
    for e in elements_2I:
        if np.allclose(e, curr, atol=1e-10):
            powers.append(e)
            break
    curr = qmul(curr, a)

# Generate group: {a^k, a^k * b : k=0..9}
group_2D5 = []
group_keys = set()
for k in range(10):
    for do_b in [False, True]:
        elem = qmul(powers[k], b) if do_b else powers[k]
        for e in elements_2I:
            if np.allclose(e, elem, atol=1e-10):
                elem = e
                break
        key = qkey(elem)
        if key not in group_keys:
            group_keys.add(key)
            group_2D5.append(elem)

assert len(group_2D5) == 20, f"|2D₅| = {len(group_2D5)}, expected 20"
for g in group_2D5:
    assert qkey(g) in keys_2I
print(f"2D₅ ⊂ 2I verified: |2D₅| = 20, all elements in 2I")

# =============================================================
# 4. 2D₅ conjugacy classes
# =============================================================


def conj_classes(elements):
    remaining = list(range(len(elements)))
    classes = []
    while remaining:
        rep_idx = remaining[0]
        rep = elements[rep_idx]
        cls, new_rem = [], []
        for idx in remaining:
            g = elements[idx]
            is_conj = any(np.allclose(qmul(qmul(h, g), qinv(h)), rep, atol=1e-10)
                          for h in elements)
            (cls if is_conj else new_rem).append(idx)
        classes.append(cls)
        remaining = new_rem
    return classes


classes_2D5 = conj_classes(group_2D5)
class_sizes_2D5 = [len(c) for c in classes_2D5]
assert len(classes_2D5) == 8

print(f"\n2D₅: 8 conjugacy classes, sizes = {class_sizes_2D5}")
for i, cls in enumerate(classes_2D5):
    rep = group_2D5[cls[0]]
    tr = 2 * rep[0]
    print(f"  C{i}: size {len(cls)}, trace = {tr:.6f}")

# Identify b-class vs ab-class
c_b_idx, c_ab_idx = None, None
ab = qmul(a, b)
for e in elements_2I:
    if np.allclose(e, ab, atol=1e-10):
        ab = e
        break
for i, cls in enumerate(classes_2D5):
    if len(cls) == 5:
        for idx in cls:
            g = group_2D5[idx]
            if np.allclose(g, b, atol=1e-10):
                c_b_idx = i
            if np.allclose(g, ab, atol=1e-10):
                c_ab_idx = i
print(f"  Class with b: C{c_b_idx}, class with ab: C{c_ab_idx}")

# =============================================================
# 5. 2D₅ character table (Dic₅)
# =============================================================

# Standard class order:
# {1}(1), {a,a⁹}(2), {a²,a⁸}(2), {a³,a⁷}(2), {a⁴,a⁶}(2), {-1}(1), {b,...}(5), {ab,...}(5)

our_to_std = {}
for i, cls in enumerate(classes_2D5):
    size = len(cls)
    tr = 2 * group_2D5[cls[0]][0]
    if size == 1 and tr > 0:
        our_to_std[i] = 0
    elif size == 1 and tr < 0:
        our_to_std[i] = 5
    elif size == 2 and abs(tr - phi) < 0.01:
        our_to_std[i] = 1
    elif size == 2 and abs(tr - inv_phi) < 0.01:
        our_to_std[i] = 2
    elif size == 2 and abs(tr + inv_phi) < 0.01:
        our_to_std[i] = 3
    elif size == 2 and abs(tr + phi) < 0.01:
        our_to_std[i] = 4
    elif i == c_b_idx:
        our_to_std[i] = 6
    elif i == c_ab_idx:
        our_to_std[i] = 7

# Abelianization Z₄: phi(a) = 2, phi(b) = 1
phi_vals_std = [0, 2, 0, 2, 0, 2, 1, 3]

# 1D characters: chi_k(g) = i^(k * phi(g))
CHAR_2D5 = {}
for k in range(4):
    std_vals = [np.exp(2j * np.pi * k * p / 4) for p in phi_vals_std]
    CHAR_2D5[f'chi_{k}'] = np.array([std_vals[our_to_std[i]]
                                      for i in range(8)], dtype=complex)

# 2D characters: psi_m(a^n) = 2cos(pi*m*n/5), psi_m(a^n*b) = 0
for m in range(1, 5):
    std_vals = [2 * np.cos(np.pi * m * n / 5) for n in range(6)] + [0, 0]
    CHAR_2D5[f'psi_{m}'] = np.array([std_vals[our_to_std[i]]
                                      for i in range(8)], dtype=complex)

# Verify orthogonality
print("\nOrthogonality check (2D₅):")
all_ok = True
for n1 in CHAR_2D5:
    for n2 in CHAR_2D5:
        ip = sum(class_sizes_2D5[i] * np.conj(CHAR_2D5[n1][i]) * CHAR_2D5[n2][i]
                 for i in range(8)) / 20
        expected = 1 if n1 == n2 else 0
        if abs(ip - expected) > 0.01:
            print(f"  FAIL: <{n1},{n2}> = {ip}")
            all_ok = False
if all_ok:
    print("  All ⟨χᵢ,χⱼ⟩ = δᵢⱼ ✓")

# Spinorial status
minus1_2D5 = [i for i in range(8) if our_to_std[i] == 5][0]
print("\nSpinorial status (2D₅):")
for name in ['chi_0', 'chi_1', 'chi_2', 'chi_3', 'psi_1', 'psi_2', 'psi_3', 'psi_4']:
    v = CHAR_2D5[name][minus1_2D5]
    spin = 'S' if v.real < -0.5 else 'T'
    dim = 2 if name.startswith('psi') else 1
    print(f"  {name}({spin}): dim {dim}, χ(-1) = {v:.0f}")

# =============================================================
# 6. Branching rules: decompose restricted 2I characters
# =============================================================


def find_2I_class(elem):
    k = qkey(elem)
    for i, c in enumerate(classes_2I):
        if k in c['keys']:
            return i
    for e2I in elements_2I:
        if np.allclose(e2I, elem, atol=1e-10):
            k2 = qkey(e2I)
            for i, c in enumerate(classes_2I):
                if k2 in c['keys']:
                    return i
    raise ValueError(f"Element not found in 2I classes")


print("\n" + "=" * 70)
print("BRANCHING RULES: 2I → 2D₅ (icosahedral → pentagonal)")
print("=" * 70)
print()

irrep_order_2I = ['A', 'T', 'Tp', 'G', 'H', 'F1', 'F2', 'Gp', 'D']
irrep_order_2D5 = ['chi_0', 'chi_2', 'chi_1', 'chi_3',
                    'psi_1', 'psi_2', 'psi_3', 'psi_4']
labels_2D5 = {
    'chi_0': 'χ₀(T)', 'chi_1': 'χ₁(S)', 'chi_2': 'χ₂(T)', 'chi_3': 'χ₃(S)',
    'psi_1': 'ψ₁(S)', 'psi_2': 'ψ₂(T)', 'psi_3': 'ψ₃(S)', 'psi_4': 'ψ₄(T)'
}

id_cls_idx = [i for i in range(8) if our_to_std[i] == 0][0]

for name_2I in irrep_order_2I:
    # Restricted character on 2D₅ classes
    chi_res = np.zeros(8, dtype=complex)
    for i, cls in enumerate(classes_2D5):
        rep = group_2D5[cls[0]]
        ci = find_2I_class(rep)
        chi_res[i] = irreps_2I[name_2I][ci]

    dim = int(round(chi_res[id_cls_idx].real))

    # Decompose via character inner products
    decomp = []
    dim_check = 0
    for irr in irrep_order_2D5:
        ip_val = sum(class_sizes_2D5[i] * np.conj(CHAR_2D5[irr][i]) * chi_res[i]
                     for i in range(8)) / 20
        m = int(round(ip_val.real))
        assert abs(ip_val.imag) < 0.1 and abs(ip_val.real - m) < 0.1, \
            f"{name_2I}, {irr}: multiplicity not integer: {ip_val}"
        if m > 0:
            d = 2 if irr.startswith('psi') else 1
            dim_check += m * d
            decomp.append(f"{'%d' % m if m > 1 else ''}{labels_2D5[irr]}")

    assert dim_check == dim, f"{name_2I}: dim mismatch {dim_check} vs {dim}"
    decomp_str = ' ⊕ '.join(decomp)
    print(f"  {name_2I:>3}({spin_2I[name_2I]}) dim {dim}:  {decomp_str}")

# =============================================================
# 7. Physics summary
# =============================================================

print()
print("=" * 70)
print("PHYSICS SUMMARY")
print("=" * 70)
print()
print("Scalar quantization sectors = 1D characters of π₁.")
print("In icosahedral phase (I): Q₈ ⊂ 2I → no 1D spinorial chars → obstruction.")
print("In pentagonal phase (D₅): Q₈ ⊄ 2D₅ → χ₁, χ₃ are 1D spinorial → re-entrance.")
print()
print("Which 2I irreps produce new 1D spinorial sectors of 2D₅?")

for name_2I in irrep_order_2I:
    chi_res = np.zeros(8, dtype=complex)
    for i, cls in enumerate(classes_2D5):
        rep = group_2D5[cls[0]]
        ci = find_2I_class(rep)
        chi_res[i] = irreps_2I[name_2I][ci]
    for irr in ['chi_1', 'chi_3']:
        ip_val = sum(class_sizes_2D5[i] * np.conj(CHAR_2D5[irr][i]) * chi_res[i]
                     for i in range(8)) / 20
        m = int(round(ip_val.real))
        if m > 0:
            print(f"  {name_2I}({spin_2I[name_2I]}) dim {int(irreps_2I[name_2I][0])} "
                  f"→ contains {labels_2D5[irr]} (×{m})")

print()
print("Only D (rank 6, largest spinorial irrep of 2I) splits to produce")
print("scalar spinorial sectors. F₁, F₂ remain rank-2 (ψ₁, ψ₃).")
print("G' splits into ψ₁ ⊕ ψ₃ — still inaccessible to scalar quantization.")

# Dimension checks
dim_sq_2I = sum(int(irreps_2I[n][0]) ** 2 for n in names_2I)
dim_sq_2D5 = sum(int(round(abs(CHAR_2D5[n][id_cls_idx]))) ** 2 for n in CHAR_2D5)
print(f"\nDimension checks:")
print(f"  Σ dim²(2I)  = {dim_sq_2I} = |2I| = 120 {'✓' if dim_sq_2I == 120 else '✗'}")
print(f"  Σ dim²(2D₅) = {dim_sq_2D5} = |2D₅| = 20 {'✓' if dim_sq_2D5 == 20 else '✗'}")
